### ISSUE TITLE
Unable to click on Vanilla game elements after latest update.

### ISSUE THREAD

**Issue by eddy-vericlock** [linuxgurugamer/ClickThroughBlocker#12]
Version 1.10.5 and 1.10.6 seem to prevent the vanilla UI elements from being clickable.  After loading a save file I can click on all the buttons added by mods and they work.  But I couldn't click on any of the buildings and even the "Game Pause" button in the top right wasn't clickable.  I had to alt-F4 to close the game at that point.  Downgrading to 0.1.9.5 fixes the issue.

I'm running KSP 1.10.0.2917.  My mod list:
[x] Science! Continued (xScienceContinued 5.26)
AmpYear (AmpYearPowerManager 1:V1.5.7.0)
Aviation Lights (AviationLights 1:v4.1.0)
B9 Part Switch (B9PartSwitch v2.16.0)
Background Resources (BackgroundResources 1:V0.15.0.0)
Chatterer (Chatterer 0.9.99)
ClickThrough Blocker (ClickThroughBlocker 0.1.9.5)
Community Category Kit (CommunityCategoryKit 5.1.0.0)
Community Resource Pack (CommunityResourcePack 1.3.0.0)
Connected Living Space (ConnectedLivingSpace 2.0.0.5)
Contract Configurator (ContractConfigurator 1.28.2)
Contract Pack: Bases and Stations Reborn (ContractConfigurator-KerbinSpaceStation 2:3.7.2.2)
Contract Pack: Clever Sats (ContractConfigurator-CleverSats 1.4)
Contract Pack: Exploration Plus (ContractConfigurator-ExplorationPlus 2.0.1)
Contract Pack: Field Research (ContractConfigurator-FieldResearch 1.2.1)
Contract Pack: RemoteTech (ContractConfigurator-RemoteTech 2.1.4)
Deadly Reentry Continued (DeadlyReentry v7.8.0)
Distant Object Enhancement Continued (DistantObject v2.0.0.2)
Distant Object Enhancement Continued default config (DistantObject-default v2.0.0.2)
Docking Port Alignment Indicator (DockingPortAlignmentIndicator 6.9.1)
Environmental Visual Enhancements (EnvironmentalVisualEnhancements 2:EVE-1.8.0-2)
Environmental Visual Enhancements - Stock Planet Config files (EnvironmentalVisualEnhancements-HR 2:EVE-1.2.2-1)
Ferram Aerospace Research Continued (FerramAerospaceResearchContinued 3:0.15.11.4)
Infernal Robotics - Next (InfernalRoboticsNext v3.0.0)
Kerbal Alarm Clock (KerbalAlarmClock v3.13.0.0)
Kerbal Attachment System (KAS 1.6)
Kerbal Changelog (KerbalChangelog v1.3.0)
Kerbal Inventory System (KIS 1.25)
Kerbal Joint Reinforcement - Next (KerbalJointReinforcementNext v4.1.15)
Kerbal Planetary Base Systems (KerbalPlanetaryBaseSystems v1.6.11)
KSP AVC (KSP-AVC 1.4.1.4)
MechJeb 2 (MechJeb2 2.9.2.0)
ModularFlightIntegrator (ModularFlightIntegrator 1.2.7.0)
Module Manager (ModuleManager 4.0.2)
Near Future IVA Props (NearFutureProps 1:0.6.2)
PlanetShine (PlanetShine 0.2.6.3)
PlanetShine - Default configuration (PlanetShine-Config-Default 0.2.6.3)
Procedural Fairings (ProceduralFairings 1:v1.8.2)
RasterPropMonitor (RasterPropMonitor 1:v0.31.3)
RasterPropMonitor Core (RasterPropMonitor-Core 1:v0.31.3)
RealChute Parachute Systems (RealChute v1.4.7.6)
RemoteTech (RemoteTech v1.9.6)
REPOSoftTech-Agencies (REPOSoftTech-Agencies V1.5.7.0)
ReStock (ReStock 1.1.2)
SCANsat (SCANsat v20.1)
scatterer (Scatterer 3:v0.0610)
Scatterer Default Config (Scatterer-config 3:v0.0610)
Scatterer Sunflare (Scatterer-sunflare 3:v0.0610)
ScienceAlert ReAlerted (ScienceAlert 1.9.8.8)
SmokeScreen - Extended FX Plugin (SmokeScreen 2.8.14.0)
Stockalike Station Parts Expansion Redux (StationPartsExpansionRedux 1.3.5)
TAC Fuel Balancer (TacFuelBalancer v2.21.5.1)
TAC Life Support (TACLS) (TACLS 1:V0.15.0.0)
Toolbar (Toolbar 1:1.8.0.5)
Toolbar Controller (ToolbarController 1:0.1.9.4)
TriggerAu Flags (TriggerAu-Flags v2.10.0.0)
Waypoint Manager (WaypointManager 2.8.2.3)
Zero MiniAVC (ZeroMiniAVC 1:1.1.0.1)

**Comment by linuxgurugamer** [comment]
That was a bug which was fixed in 0.1.10.6,
Please try it again, and do the following:

1. Find the new toolbar button which is for the ClickThroughBlocker (looks like a mouse) and click it, it clears all the input locks
2. I need a complete Player.log of when this happens.
 

Thanks

**Comment by eddy-vericlock** [comment]
I found the toolbar button, pressed it and it said "All input locks cleared" and then it worked normally after that.

Here my log files.  I loaded the save game, tried to click on one of the buildings then clicked on the clear input lock button, then clicked on a building then alt-f4.
https://www.dropbox.com/s/r4eblr4u6b0nnij/Player.log?dl=0
https://www.dropbox.com/s/50jemebj2as01mb/KSP.log?dl=0

**Comment by linuxgurugamer** [comment]
First, are you using CTB in FocusFollowsMouse or FocusFollowsClick?

I see from the log file that you are adding mods to your steam directory.  This is not a great idea, since it means that when Steam updates KSP, your game will most likely be broken.

What you should do is copy the entire KSP folder from steam to another location on your disk.  KSP does not have any DRM, and this is the preferred way to run mods.

Your KSP folder is at:   C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program

Once you do that, and have successfully run the game from the new location, then delete (yes, I do mean delete) the entire KSP folder from the Steam folder, then tell steam to verify the files.  That will get Steam to reinstall the game in the same location.

This now gives you a clean copy of KSP.

Copy it to another location, and with CKAN, add just the ClickThroughBlocker, then start the game and see if it's working or not.

I don't see anything in the log file which appears to be significant regarding CTB, although I do see a number of issues.  I'd like to rule out any mod interactions which might be happening.

Assuming it works for you in the new install, then start adding mods a few at a time and testing after each set.  It's a bit tedious, but I and many other people are using the same version of CTB without any problem, so we need to figure out what's the difference.

**Comment by eddy-vericlock** [comment]
I was using it in FocusFollowsMouse.  So I downloaded a clean copy of Kerbal, renamed the folder, and installed only ClickThroughBlocker.  I was surprised to find it still had the same problem, but only on the first time loading.  Subsequent restarts of Kerbal were fine.  I could reproduce the problem by uninstalling and reinstalling mods using CKAN which I assume is wiping out the settings file.  After that it would fail on the next load.

[Player.log](https://github.com/linuxgurugamer/ClickThroughBlocker/files/4888841/Player.log)

If no one else is having the problem, it's not an issue for me as I can make it work.

**Comment by Toasted-Rice** [comment]
Hi, I'm having the same issue. As soon as I set it to FocusFollowsMouse, I can't click on any vanilla elements past the main menu. I can't even click on saves or create a new save. Also where an I find the log? Is it KSP.log?

**Comment by linuxgurugamer** [comment]
Fixed in next release
